baseURL: "https://monumental-marzipan-fe145d.netlify.app/"
languageCode: en-us
title: I'm Gianluca
theme: PaperMod
author: Gianluca Beninato

params:
  homeInfoParams:
    Title: "Ma che idea!"
    Content: Benvenuti nel mio sito. Appena posso **leggo**. Ogni mattina **corro**.
  socialIcons:
    - name: facebook
      url: "https://facebook.com"
    - name: twitter
      url: "https://twitter.com"
    - name: github
      url: "https://github.com"
    - name: strava
      url: "https://strava.com"

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true

  comments: true

menu:
  main:
    - identifier: categorie
      name: Categorie
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

